[package]
name = "csharp-interop"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = "0.14.14"
interoptopus_backend_csharp = "0.14.14"